### ISSUE TITLE
Error while preprocessing data

### ISSUE THREAD

**Issue by Yuren-Zhong** [arielephrat/vid2speech#2]
I failed to preprocess the data.

```
$ python process_data.py
Processing video and audio data...
Face detection error in ../dataset/lbwy8p.mpg frame: 0
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /feedstock_root/build_artefacts/opencv_1510577904808/work/opencv-3.3.0/modules/imgproc/src/imgwarp.cpp, line 3483
Traceback (most recent call last):
  File "process_data.py", line 113, in <module>
    main()
  File "process_data.py", line 100, in main
    vidctr = process_video(join(datapath,vf), viddata, vidctr, faceCascade)
  File "process_data.py", line 52, in process_video
    face = cv2.resize(face,(FRAME_COLS,FRAME_ROWS))
cv2.error: /feedstock_root/build_artefacts/opencv_1510577904808/work/opencv-3.3.0/modules/imgproc/src/imgwarp.cpp:3483: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize
```

**Comment by 1924344285** [comment]
> I failed to preprocess the data.
> 
> ```
> $ python process_data.py
> Processing video and audio data...
> Face detection error in ../dataset/lbwy8p.mpg frame: 0
> OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /feedstock_root/build_artefacts/opencv_1510577904808/work/opencv-3.3.0/modules/imgproc/src/imgwarp.cpp, line 3483
> Traceback (most recent call last):
>   File "process_data.py", line 113, in <module>
>     main()
>   File "process_data.py", line 100, in main
>     vidctr = process_video(join(datapath,vf), viddata, vidctr, faceCascade)
>   File "process_data.py", line 52, in process_video
>     face = cv2.resize(face,(FRAME_COLS,FRAME_ROWS))
> cv2.error: /feedstock_root/build_artefacts/opencv_1510577904808/work/opencv-3.3.0/modules/imgproc/src/imgwarp.cpp:3483: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize
> ```

May i ask you have you solved this problem yet?
